### ISSUE TITLE
find-aspect-ratio error: Could not find a given aspect ratio.

### ISSUE THREAD

**Issue by deadcoder0904** [spencermountain/fit-aspect-ratio#4]
Hey Spencer, really nice project.

Aspect Ratio has been fucking me up for a couple of days now.

I was wondering if this package can make a centered rectangle like https://codepen.io/chriscoyier/pen/BZNoev (try resizing the window)

I want to make a browser window like the following in Canvas:

![browser-window](https://user-images.githubusercontent.com/16436270/103132710-0cfb4a80-46cc-11eb-9d5b-92650756ecd3.png)

The browser window should be responsive so aspect ratio is what I need I think.

Would you mind telling me how to do it? I want the width to have a little bit of padding from either sides & height to be just a little above 50px from the bottom.

I tried doing the following:

```js
const width = 1366
const height = 768

aspect({
  width: window.innerWidth * 0.8, /* this allows for 20% padding on either sides */
  ratio: '16/9'
})
```

But I get the error:

> find-aspect-ratio error: Could not find a given aspect ratio.

Not sure if this is the package that will solve my problem but would love to know your opinions as you've probably spent more time on aspect ratio :)

**Comment by spencermountain** [comment]
hi Akshay, yeah, this is an interesting problem that has stumped me before too.
I'd use the css method from chris's example, instead of something like this library.
You can set padding-top to whatever percent you'd like, and just let the css do the hard-work.
(16:9 would be 9/16= 56%) - 

if you're doing it in canvas, and the canvas element is being a pain, i'd set the canvas to 100%, and wrap it in a div with `padding-top:56%`.

Honestly, it's pretty hard getting these things working together. Way harder than it should be.
Best of luck
cheers

**Comment by spencermountain** [comment]
to avoid the error in this lib, it's `ratio: '16:9'`

**Comment by deadcoder0904** [comment]
Cool, thanks man. It's been a week now & this problem still isn't being solved using JS 😂

The height suddenly gets zero if I use 16:9 ratio but I'll definitely try your method. That sounds simple & should work. Thanks for answering :)
